version : "3.8"

volumes:
  postgresql-data:
  artifact-store:

services:
  mlflow-db:
    container_name : mlflow-backend-store
    image : postgres:13.3
    env_file:
      -.envs/.postgres

  mlflow-server:
    image : local-mlflow-tracking-server
    container_name : local-mlflow-tracking-server
    build:
      context : .
      dockerfile : ./docker/dockerfile
      args:
        MLFLOW_ARTIFACT_STORE : ${MLFLOW_ARTIFACT_STORE}
      ports : 
        - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:$LOCAL_DEV_MLFLOW_SERVER_PORT}
      sepends_on:
        -mlflow-db
      env_file:
        -.envs/.postgres
        -.envs/.mlflow-common
        -.envs/.mlflow-dev

      volumes:
        -./:/app
        - artifact-store:$(MLFLOW_ARTIFACT_STORE)

      ipc : host
      init : true
      