version: "3.8"

volumes:
  postgresql-data:
  artifact-store:

services:
  mlflow-db:
    image: postgres:13.3
    container_name: mlflow-backend-store
    env_file: .env
      #- .envs/.postgres

  mlflow-server:
    image: local-mlflow-tracking-server
    container_name: local-mlflow-tracking-server
    env_file: .env
      #- .envs/.postgres
      # - /envs/mlflow-common.env
      #- .envs/.mlflow-dev
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args: 
        MLFLOW_ARTIFACT_STORE : ${MLFLOW_ARTIFACT_STORE}
    ports: 
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    depends_on:
      - mlflow-db
    volumes:
      - ./:/app
      - artifact-store:${MLFLOW_ARTIFACT_STORE}

    ipc: host
    init: true
      